version: 0.2
env:
    secrets-manager:
      TOKEN: mavenhelloworld:maven-helloworld1
      
      build:
    commands:
      - mvn verify sonar:sonar -Dsonar.projectKey=maven-helloworld -Dsonar.organization=maven-helloworld -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=$TOKEN
      - sleep 5
      - |- 
        quality_status=$(curl -s -u $TOKEN: https://sonarcloud.io/api/qualitygates/project_status?projectKey=maven-helloworld | jq -r '.projectStatus.status')
        echo "SonarCloud analysistatus is $quality_status"; 
        if [ $quality_status = "ERROR" ] ; then exit 1;fi
artifacts:
    files:
      - '**/*'
